### ISSUE TITLE
Project file does not exist - error

### ISSUE THREAD

**Issue by bendulum** [rse/node-enigmavirtualbox#3]
Hello, I am using this tool to generate a single exe file from my node project, as [described here](https://github.com/nwjs/nw.js/wiki/How-to-package-and-distribute-your-apps#an-alternative-way-to-make-an-executable-file-in-windows).

I have a batch file that downloads/unzips node-webkit and my-project and combines the files as expected. Then the batch file uses enigma to generate the desired exe. 

For some reason this process has stopped working and I get "**project file does not exist**" error.

The relevant part of the batch file looks like this:

```
@echo off
setlocal EnableDelayedExpansion
>log.txt (
    [...]
    enigmavirtualbox gen app.evp swellgibson.exe combined.exe d3dcompiler_47.dll ffmpegsumo.dll icudtl.dat libEGL.dll libGLESv2.dll nw.pak nwjc.exe pdf.dll
    enigmavirtualbox cli app.evp
    [...]
)
exit
```
- When I check inside these folders, all required files are present.
- npm list -g enigmavirtualbox yields `enigmavirtualbox@0.9.3`
- The configuration file "app.evp" is generated correctly, [see here](http://pastebin.com/uqM9uEfY)
- The output of `%cd%` seems correct, so enigma should be looking in the correct folder
- I am using `node v0.12.0`

Full error output:

```
ERROR: failed to execute command "cli": 
Error: Command failed: C:\Users\<username>\AppData\Roaming\npm\node_modules\enigmavirtualbox\enigmavb\enigmavbconsole.exe app.evp
Enigma Virtual Box 7.20 Build 20141013
Copyright (C) Vladimir Sukhov
Web: http://enigmaprotector.com/
EMail: vbox@enigmaprotector.com
Usage to pack the project: enigmavbconsole project.evb
Usage to make the package: enigmavbconsole project.evb package.evb.template output_package.dat
Project file does not exist!
```

Any ideas why this might have stopped working?

**Comment by bendulum** [comment]
I found out it is a problem with `setlocal EnableDelayedExpansion`. The value of `%cd%` is correct when running the enigma commands, but enigma seems to look "somewhere else" for the files, probably in the directory where the batch file itself resides.

**Comment by jaredallard** [comment]
@bendulum Try using !CD!
