### ISSUE TITLE
Access violation when trying to run enigmavb.exe

### ISSUE THREAD

**Issue by saitonakamura** [rse/node-enigmavirtualbox#6]
I get an `Access violation at address 00559F39A in module 'enigmavb.exe'. Read of address 00000000`. Of course address is changing over the time. Same error when running `evigmavbconsole.exe`. I trying `7.50` and `7.40` version. I'm using Windows 10 by the way. 

I beleive that it is an issue within enigmavb itself, and you have a little to do with it. But there's probability that some old version would work.

**Comment by bendulum** [comment]
For what it's worth: I'm getting a similar error `Access violation at address 00446FCC in module 'enigmavbconsole.exe'. Read of address 7BA874C2`. I'm creating my Enigma configuration file with https://www.npmjs.com/package/generate-evb 
Trying to create a single executable out of a packaged Electron app. 
It used to work, not sure what exactly changed that could have caused this.

node 6.2.2
npm 3.9.5
"electron-packager": "^8.0.0",
"enigmavirtualbox": "^0.9.6",
"generate-evb": "^0.6.0"
Windows 10

**Comment by HijackHornet** [comment]
Getting the same issue while trying to add a registery 
`Access violation at address 0055A298 in module 'enigmavb.exe' at address FFFFFFE `
