### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by Speuta** [rse/node-enigmavirtualbox#7]
Hi,
Thanks for this module ! ;)
I've got an error:
`ERROR: failed to execute command "cli": Error: stdout maxBuffer exceeded`
Is it possible to have a "maxBuffer" option ?

**Comment by rse** [comment]
I've now increased it from 200KB (default) to 10MB. This should resolve the problem, even if there is still no explicit option for setting the buffer to an arbitrary size.

**Comment by Speuta** [comment]
Thank you !
